version: '3.8'

services:
  web:
    build:
      context: ./django_react_roomscheduler
      dockerfile: roomschedulerapi/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_react_roomscheduler:/usr/src/app/
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15.6
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./django_react_roomscheduler/static:/usr/src/app/static
      - ./django_react_roomscheduler/media:/usr/src/app/media
    depends_on:
      - web

volumes:
  postgres_data:
