# Generated by Django 5.0.1 on 2024-02-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.IntegerField()),
                ('floor_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('classroom_id', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('instructor', models.CharField(max_length=25)),
                ('first_day', models.DateField()),
                ('last_day', models.DateField()),
                ('course_name', models.CharField(max_length=25)),
                ('term', models.CharField(max_length=25)),
                ('credits', models.IntegerField()),
                ('subject', models.CharField(max_length=25)),
                ('course_capacity', models.IntegerField()),
                ('waitlist_capacity', models.IntegerField()),
                ('course_total', models.IntegerField()),
                ('waitlist_total', models.IntegerField()),
                ('total_enrollment', models.IntegerField()),
                ('course_level', models.IntegerField()),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_id', models.IntegerField()),
                ('building_id', models.IntegerField()),
            ],
        ),
    ]
