# pull official base image
FROM python:3.11.4-slim-buster

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# update and install dependencies
RUN apt-get update && \
    apt-get install -y netcat && \
    pip install --upgrade pip

# install dependencies
COPY ../requirements.txt .
RUN pip install -r requirements.txt

# copy entrypoint.sh
COPY ../entrypoint.sh .
RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# copy project
COPY . .

# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
