# Generated by Django 5.0.1 on 2024-02-13 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomschedulerapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='classroom_id',
            new_name='classroom',
        ),
    ]
