# Generated by Django 5.0.1 on 2024-02-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomschedulerapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='floor_id',
            new_name='floor',
        ),
    ]
