# Generated by Django 5.0.1 on 2024-03-21 02:01

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomschedulerapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptiScore',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('prime_time_score', models.IntegerField(default=0)),
                ('capacity_score', models.IntegerField(default=0)),
                ('instructor_score', models.IntegerField(default=0)),
                ('instructor_methods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('double_booking_score', models.IntegerField(default=0)),
                ('idle_time', models.IntegerField(default=0)),
                ('idle_time_score', models.IntegerField(default=0)),
                ('double_booking', models.BooleanField(default=False)),
                ('overall_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='term',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='roomschedulerapi.term'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='optimization_score',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='roomschedulerapi.optiscore'),
        ),
    ]
