# Generated by Django 5.0.1 on 2024-02-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomschedulerapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_name',
            field=models.CharField(default=int, max_length=100),
            preserve_default=False,
        ),
    ]
