# Generated by Django 5.0.1 on 2024-02-12 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomschedulerapi', '0002_rename_floor_id_classroom_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='building_id',
            new_name='building',
        ),
    ]
