# Generated by Django 5.0.1 on 2024-02-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roomschedulerapi", "0002_rename_classroom_id_course_classroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="classroom_name",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name="classroom",
            name="floor_name",
            field=models.CharField(default=0),
        ),
        migrations.AddField(
            model_name="floor",
            name="building_name",
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name="building",
            name="building_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="notes",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_level",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.CharField(default=""),
        ),
    ]
