# Generated by Django 5.0.1 on 2024-03-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomschedulerapi', '0002_optiscore_classroom_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiscore',
            name='prime_time_utilization',
            field=models.IntegerField(default=0),
        ),
    ]
