# Generated by Django 5.0.1 on 2024-02-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomschedulerapi', '0002_building_building_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_room_number',
            field=models.IntegerField(default=0),
        ),
    ]
