# Generated by Django 5.0.1 on 2024-02-14 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "roomschedulerapi",
            "0003_classroom_classroom_name_classroom_floor_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="course_total",
        ),
        migrations.RemoveField(
            model_name="course",
            name="classroom",
        ),
        migrations.AddField(
            model_name="course",
            name="classroom",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="roomschedulerapi.classroom",
            ),
        ),
    ]
