# Generated by Django 5.0.1 on 2024-03-21 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomschedulerapi', '0003_optiscore_prime_time_utilization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optiscore',
            name='idle_time',
        ),
    ]
