# Generated by Django 5.0.1 on 2024-02-08 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomschedulerapi', '0003_alter_classroom_class_room_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='class_room_number',
            new_name='classroom_number',
        ),
    ]
