# Generated by Django 5.0.1 on 2024-02-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roomschedulerapi", "0003_alter_classroom_class_room_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.CharField(default=""),
        ),
    ]
