# Generated by Django 5.0.1 on 2024-02-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomschedulerapi', '0004_remove_course_course_total_remove_course_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
