# Generated by Django 5.0.1 on 2024-03-21 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomschedulerapi', '0004_remove_optiscore_idle_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='optimization_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomschedulerapi.optiscore'),
        ),
    ]
