# Generated by Django 5.0.1 on 2024-02-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "roomschedulerapi",
            "0004_remove_course_course_total_remove_course_classroom_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="classroom_number",
            field=models.CharField(default=0),
        ),
    ]
