# Generated by Django 5.0.1 on 2024-04-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomschedulerapi', '0004_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_password_admin',
            field=models.BooleanField(default=False),
        ),
    ]
