# Generated by Django 5.0.1 on 2024-03-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomschedulerapi', '0005_alter_classroom_optimization_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiscore',
            name='capacity_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='optiscore',
            name='double_booking_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='optiscore',
            name='idle_time_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='optiscore',
            name='instructor_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='optiscore',
            name='overall_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='optiscore',
            name='prime_time_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='optiscore',
            name='prime_time_utilization',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
