# Generated by Django 5.0.1 on 2024-02-29 21:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roomschedulerapi", "0005_alter_classroom_classroom_number"),
        ("roomschedulerapi", "0005_building_image_url"),
    ]

    operations = []
