# Generated by Django 5.0.1 on 2024-02-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roomschedulerapi", "0006_alter_course_course_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="building_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="floor",
            name="floor_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
