# Generated by Django 5.0.1 on 2024-02-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "roomschedulerapi",
            "0007_alter_building_building_name_alter_floor_floor_name",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="floor",
            name="floor_name",
            field=models.CharField(max_length=50),
        ),
    ]
