# Generated by Django 5.0.1 on 2024-02-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomschedulerapi', '0007_alter_classroom_classroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='image_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
