# Generated by Django 5.0.1 on 2024-02-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roomschedulerapi", "0008_alter_floor_floor_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="classroom_name",
            field=models.CharField(default=" ", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="floor",
            name="floor_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
