# Generated by Django 5.0.1 on 2024-02-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roomschedulerapi", "0010_alter_floor_floor_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="classroom_name",
            field=models.CharField(max_length=100),
        ),
    ]
