# Generated by Django 5.0.1 on 2024-02-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roomschedulerapi", "0011_alter_classroom_classroom_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="floor_name",
            field=models.CharField(default=0),
        ),
    ]
