# Generated by Django 5.0.1 on 2024-02-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roomschedulerapi", "0012_classroom_floor_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="floor",
            name="building_name",
            field=models.CharField(default=0, max_length=50),
        ),
    ]
